version: '3.8'
services:
  news-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: news-app
    environment:
      - NEWS_API_KEY=e6ef628f19614327ad9dfce593be8628